# Generated by Django 5.1.7 on 2025-03-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_uploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploads",
            name="receiver",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
