# Generated by Django 5.1.7 on 2025-03-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_uploads_receiver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Send_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("receiver", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="uploads",
            name="receiver",
        ),
    ]
