# Generated by Django 5.1.7 on 2025-03-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_send_data_remove_uploads_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="send_data",
            name="request",
            field=models.CharField(default=0, max_length=2),
        ),
    ]
