# Generated by Django 5.1.7 on 2025-03-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_send_data_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="send_data",
            name="done",
            field=models.CharField(default=0, max_length=2),
        ),
    ]
